# Ref :https://www.youtube.com/watch?v=DeZjkCtttss
site_name: Crystal EMR
theme:
  name: material
  favicon: assets/images/favicon/favicon-16x16.png
  logo: assets/images/favicon/android-chrome-512x512.png
  font:
    text: Roboto  
  
         

  
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: amber
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: blue grey
      accent: deep orange


  features:
    - navigation.instant # Optional, makes navigation faster
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.path    
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.tabs.link
    - content.code.copy
    - content.tooltips   # Optional, adds tooltips on hover
    - header.autohide



plugins:
  - search
  - tags
  # - mike:
  #     # These fields are all optional; the defaults are as below...
  #     alias_type: symlink
  #     redirect_template: null
  #     deploy_prefix: ''
  #     canonical_version: null
  #     version_selector: true
  #     css_dir: css
  #     javascript_dir: js


extra:
  version:
    provider: mike
  generator: false

  social:
    # - icon: fontawesome/brands/github 
    #   link: https://github.com/rhd1703
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@crystal8383
    - icon: fontawesome/solid/paper-plane
      link: mailto:<info@crystalemr.com>


# # Repository
# repo_name: rhd1703/CrystalEMR-docs
# repo_url: https://github.com/rhd1703/CrystalEMR-docs
# edit_uri: ""


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption 
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true  
  # - pymdownx.tasklist:
  #     clickable_checkbox: true      

extra_css:
  - assets/css/extra.css
  - assets/css/style.css


copyright: Copyright &copy; 2025 Crystal EMR


nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - Team : team.md
  - Training:
    - Log-in Page: Training/login.md
    - Token Creation: Training/tokens.md

